### ISSUE TITLE
idea: Configureable, daily push

### ISSUE THREAD

**Issue by steima** [janoliver20/CrossPlatformDev#16]
# Summary

To make the app more comfortable for the users, it could be a good idea to allow users to configure a time of the day, when they want to be pro-actively informed about the best rate near by.

## Current behaviour

Users open the app and actively search for the best rate via a list or map widget.

## Desired behaviour

A push is triggered at a configured time of the day and the user can interact with the push to jump into the app.

## Tasks

 - [ ] Discuss with the group if the feature is interesting
 - [ ] Research cross platform push
 - [ ] Settings screen (or mock via fixed time of the day)
 - [ ] Implement push
